package ghayatech.ihubs.ui.theme

import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.unit.LayoutDirection
import kotlin.String


object AppStringsProvider {
    @Composable
    fun current(): AppStrings {
        val localizationViewModel = LocalLocalizationViewModel.current
        val currentLanguage by localizationViewModel.currentLanguage.collectAsState()
        // كلما تغيرت اللغة، ستتغير النصوص هنا تلقائيًا
        return localizationViewModel.getAppStrings()
    }
}

data class AppStrings(
    val ghayatech: String,
    val login: String,
    val welcome: String,
    val sign_in_to_access: String,
    val mobile_number: String,
    val password: String,
    val confirm_password: String,
    val fullname: String,
    val major: String,
    val forget_your_password: String,
    val create_new_account: String,
    val already_have_account: String,
    val signup: String,
    val back: String,
    val verification_code: String,
    val verification_message: String,
    val receive_code: String,
    val resend_code: String,
    val s: String,
    val check_now: String,
    val verification_success: String,
    val verification_success_message: String,
    val start_experience: String,
    val search_on_hubs: String,
    val location: String,
    val payment: String,
    val current_bookings: String,
    val description: String,
    val done: String,
    val our_packages: String,
    val hours: String,
    val daily: String,
    val weakly: String,
    val monthly: String,
    val hub_features: String,
    val features: String,
    val copy: String,
    val works_hours: String,
    val works_time: String,
    val books_date: String,
    val books_time: String,
    val transfer_details: String,
    val account_number: String,
    val book_now: String,
    val order_details: String,
    val `package`: String,
    val seat_number: String,
    val left: String,
    val days: String,
    val am: String,
    val pm: String,
    val username: String,
    val remaining_time: String,
    val contactus: String,
    val our_services: String,
    val chat: String,
    val start_chatting: String,
    val search_on_services: String,
    val change_seat: String,
    val specify_details: String,
    val describe_the_details_here: String,
    val send: String,
    val profile: String,
    val bookings: String,
    val notifications: String,
    val add_fingerprint: String,
    val dark_theme: String,
    val about_us: String,
    val privacy_policy: String,
    val logout: String,
    val edit: String,
    val powered_by: String,
    val get_started: String,
    val by_creating_a_free_account: String,
    val booking_details: String,
    val gaza_al_remal: String,
    val place_photos: String,
    val effective_workspace_management: String,
    val onboarding_description: String,
    val booking_success: String,
    val booking_info: String,
    val unauthorized: String,
    val conflict: String,
    val too_many_requests: String,
    val no_internet: String,
    val server_error: String,
    val serialization: String,
    val request_timeout: String,
    val unknown: String,
    val missing_fields: String,
    val missing_phone: String,
    val no_data: String,
    val no_results: String,
    val seat_free: String,
    val show_less: String,
    val show_more: String,
    val payment_available: String,
    val booking_not_available: String,
    val evening_shift: String,
    val governorates: String,
    val regions: String,
    val free: String,
    val service_created_successfully: String,
    val language: String,
    val social_media: String,
    val update_required: String,
    val over_month_ago: String,
    val minutes: String,
    val just_now: String,
)

fun stringsFor(language: String): AppStrings = when (language) {
    "ar" -> AppStrings(
        ghayatech = "غاية تك",
        login = "تسجيل الدخول",
        welcome = "مرحباً بك",
        sign_in_to_access = "سجّل الدخول للوصول إلى حسابك",
        mobile_number = "رقم الجوال",
        password = "كلمة المرور",
        confirm_password = "تأكيد كلمة المرور",
        fullname = "الاسم الكامل",
        major = "التخصص",
        forget_your_password = "هل نسيت كلمة المرور؟",
        create_new_account = "أنشئ حساباً جديداً",
        already_have_account = "لديك حساب بالفعل!",
        signup = "إنشاء حساب",
        back = "رجوع",
        verification_code = "رمز التحقق",
        verification_message = "للوصول إلى هذا التطبيق بأمان، يرجى إدخال رمز التحقق الذي تم إرساله إلى الرقم المسجل في التطبيق.",
        receive_code = "لم تتلق الرمز بعد!",
        resend_code = "إعادة إرسال الرمز",
        s = "ث",
        check_now = "تحقق الآن",
        verification_success = "اكتملت عملية التحقق بنجاح",
        verification_success_message = "ابدأ تجربتك الآن مع أفضل تطبيق يقدم خدمات إدارة الوقت والمساحات.",
        start_experience = "ابدأ تجربتك الآن!",
        search_on_hubs = "البحث عن مساحات",
        location = "الموقع",
        payment = "الدفع",
        current_bookings = "الحجوزات الحالية",
        description = "الوصف",
        done = "تم",
        our_packages = "باقاتنا",
        hours = "ساعات",
        daily = "يومي",
        weakly = "أسبوعي",
        monthly = "شهري",
        hub_features = "مميزات المساحة:",
        features = "المميزات",
        copy = "نسخ",
        works_hours = "ساعات العمل",
        works_time = "وقت العمل",
        books_date = "تاريخ الحجز",
        books_time = "وقت الحجز",
        transfer_details = "تفاصيل التحويل",
        account_number = "رقم الحساب",
        book_now = "احجز الآن",
        order_details = "تفاصيل الطلب",
        `package` = "الباقة", // الـ ` لـ package لأنها كلمة محجوزة
        seat_number = "رقم المقعد",
        left = "متبقي",
        days = "أيام",
        am = "ص",
        pm = "م",
        username = "اسم المستخدم",
        remaining_time = "الوقت المتبقي",
        contactus = "تواصل معنا",
        our_services = "خدماتنا",
        chat = "المحادثة",
        start_chatting = "ابدأ المحادثة",
        search_on_services = "البحث عن خدماتنا",
        change_seat = "تغيير المقعد",
        specify_details = "حدد التفاصيل",
        describe_the_details_here = "صف التفاصيل هنا",
        send = "إرسال",
        profile = "الملف الشخصي",
        bookings = "الحجوزات",
        notifications = "الإشعارات",
        add_fingerprint = "إضافة بصمة",
        dark_theme = "الوضع الداكن",
        about_us = "من نحن",
        privacy_policy = "الخصوصية والسياسة",
        logout = "تسجيل الخروج",
        edit = "تعديل",
        powered_by = "بواسطة ",
        get_started = "ابدأ",
        by_creating_a_free_account = "عن طريق إنشاء حساب مجاني",
        booking_details = "تفاصيل الحجز",
        gaza_al_remal = "غزة، الرمال",
        place_photos = "صور المكان",
        effective_workspace_management = "إدارة مساحات عمل فعالة",
        onboarding_description = "نظم وقتك واستفد من مساحات العمل بكفاءة. تحكم في مهامك وابقَ على المسار الصحيح باستخدام أدوات متقدمة لإدارة الوقت والمهام.",
        booking_success = "اكتمل الحجز بنجاح.",
        booking_info = "تم إرسال معلوماتك إلى سكرتير الموقع فقط. تأكد من إتمام عملية الدفع عبر الإنترنت لتأكيد الحجز بالكامل.",
        unauthorized = "يجب أن تكون مسجلاً للدخول",
        conflict = "يوجد اختلاف في البيانات",
        too_many_requests = "محاولات كثيرة جداً",
        no_internet = "لا يوجد اتصال بالإنترنت",
        server_error = "حدث خطأ ما",
        serialization = "حدث خطأ ما",
        request_timeout = "انتهت مهلة الطلب",
        unknown = "حدث خطأ ما",
        missing_fields = "حقول مفقودة! حاول مرة أخرى من فضلك",
        missing_phone = "حقل رقم الهاتف مطلوب لإعادة تعيين كلمة المرور",
        no_data = "عذراً! لا توجد بيانات لعرضها",
        no_results = "عذراً! لا توجد نتائج",
        seat_free = "أي مقعد",
        show_less = "عرض أقل",
        show_more = "عرض المزيد",
        payment_available = "دفع بنكي",
        booking_not_available = "الحجوزات غير متاحة في هذه المساحة، لا يوجد دفع بنكي",
        evening_shift = "الفترة المسائية",
        governorates = "المحافظات",
        regions = "المناطق",
        free = "مجاني",
        service_created_successfully = "تم إنشاء الخدمة بنجاح",
        language = "اللغة",
        social_media = "مواقع التواصل : - ",
        update_required = "الرجاء تحديث التطبيق لاخر نسخة",
        over_month_ago = "منذ اكثر من شهر",
        minutes = "دقائق",
        just_now = "منذ ثوانٍ قليلة",
    )

    else -> AppStrings(
        ghayatech = "GhayaTech",
        login = "Login",
        welcome = "Welcome",
        sign_in_to_access = "sign in to access your account",
        mobile_number = "Mobile number",
        password = "Password",
        confirm_password = "Confirm password",
        fullname = "Full name",
        major = "Major",
        forget_your_password = "Forget your password?",
        create_new_account = "Create new account",
        already_have_account = "Already have an account!",
        signup = "Sign up",
        back = "Back",
        verification_code = "Verification code",
        verification_message = "To access this application securely, please enter the verification code sent to the number registered in the application.",
        receive_code = "Didn't receive code yet!",
        resend_code = "Resend the code",
        s = "s",
        check_now = "Check now",
        verification_success = "Verification process completed successfully",
        verification_success_message = "Start your experience now with the best application that provides time and hubs management services.",
        start_experience = "Start your experience now!",
        search_on_hubs = "Search on hubs",
        location = "Location",
        payment = "Payment",
        current_bookings = "Current bookings",
        description = "Description",
        done = "Done",
        our_packages = "Our packages",
        hours = "Hours",
        daily = "Daily",
        weakly = "Weakly",
        monthly = "Monthly",
        hub_features = "Hub features:",
        features = "features",
        copy = "copy",
        works_hours = "working hours",
        works_time = "working time",
        books_date = "booking date",
        books_time = "booking time",
        transfer_details = "Transfer details",
        account_number = "Account number",
        book_now = "Book now",
        order_details = "Order details",
        `package` = "Package",
        seat_number = "Seat number",
        left = "left",
        days = "days",
        am = "am",
        pm = "pm",
        username = "username",
        remaining_time = "Remaining time",
        contactus = "Contact us",
        our_services = "Our services",
        chat = "Chat",
        start_chatting = "start chatting",
        search_on_services = "Search on our services",
        change_seat = "Change seat",
        specify_details = "Specify the details",
        describe_the_details_here = "Describe the details here",
        send = "Send",
        profile = "Profile",
        bookings = "Bookings",
        notifications = "Notifications",
        add_fingerprint = "Add fingerprint",
        dark_theme = "Dark theme",
        about_us = "About us",
        privacy_policy = "Privacy and policy",
        logout = "Logout",
        edit = "Edit",
        powered_by = "Powered by ",
        get_started = "Get Started",
        by_creating_a_free_account = "by creating a free account",
        booking_details = "Booking details",
        gaza_al_remal = "Gaza, Al-Remal",
        place_photos = "Place photos",
        effective_workspace_management = "Effective workspace management",
        onboarding_description = "Organize and optimize your time within workspaces effortlessly.Take control of your tasks and stay on track with advanced tools for time and task management.",
        booking_success = "The booking was completed successfully.",
        booking_info = "Your information has been submitted to the location's secretary only.Just make sure you have completed the online payment to fully confirm the booking.",
        unauthorized = "You must be logged in",
        conflict = "There is a discrepancy in the data",
        too_many_requests = "Too many attempts",
        no_internet = "No Internet connection",
        server_error = "Something went wrong",
        serialization = "Something went wrong",
        request_timeout = "Request timeout",
        unknown = "Something went wrong",
        missing_fields = "Missing fields! try again please",
        missing_phone = "phone number field required to reset password",
        no_data = "Sorry! there is no data to display",
        no_results = "Sorry! There is no results",
        seat_free = "Any seat",
        show_less = "show less",
        show_more = "show more",
        payment_available = "Bank payment",
        booking_not_available = "Bookings are not available at this hub, no bank payment",
        evening_shift = "Evening shift",
        governorates = "Governorates",
        regions = "Regions",
        free = "Free",
        service_created_successfully = "Service created successfully",
        language = "Langauge",
        social_media = "Social Media  : - ",
        update_required = "Please update your app to the latest version",
        over_month_ago = "over a month ago",
        minutes = "minutes",
        just_now = "Just now",
    )
}

fun getLayoutDirection(languageCode: String): LayoutDirection {
    return when (languageCode) {
        "ar" -> LayoutDirection.Rtl
        else -> LayoutDirection.Ltr
    }
}